In [36]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score

In [15]:
data = pd.read_csv("C:\\Users\\20poo\\Downloads\\database_IND.csv")

In [16]:
data.sample(8)

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,other_fuel1,other_fuel2,...,year_of_capacity_data,generation_gwh_2013,generation_gwh_2014,generation_gwh_2015,generation_gwh_2016,generation_gwh_2017,generation_gwh_2018,generation_gwh_2019,generation_data_source,estimated_generation_gwh
727,IND,India,SITAPURAM POWER LIMITED,IND0000525,43.0,16.8301,80.0407,Coal,Oil,NaN,...,2019.0,NaN,NaN,NaN,250.97100,198.2880,287.00000,NaN,Central Electricity Authority,NaN
55,IND,India,BANSAGAR (IV),IND0000032,20.0,24.2230,81.2747,Hydro,NaN,NaN,...,2019.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,IND,India,BHIVPURI,IND0000057,75.0,18.9368,73.4527,Hydro,NaN,NaN,...,2019.0,NaN,299.17660,195.93540,205.55705,305.6640,314.32050,NaN,Central Electricity Authority,NaN
732,IND,India,SONE WEST CANAL,IND0000420,6.6,NaN,NaN,Hydro,NaN,NaN,...,2019.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
465,IND,India,MANIYAR,IND0000258,12.0,9.3294,76.8798,Hydro,NaN,NaN,...,2019.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,IND,India,BAGALKOT ICP,WRI1019905,28.0,16.2804,75.2250,Biomass,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
795,IND,India,TEESTA I-III,IND0000447,67.5,26.4875,88.3155,Hydro,NaN,NaN,...,2019.0,NaN,142.53773,79.62985,0.00000,130.3649,85.04265,NaN,Central Electricity Authority,NaN
314,IND,India,KALINADI SUPA,IND0000175,100.0,15.2761,74.5268,Hydro,NaN,NaN,...,2019.0,NaN,451.05340,323.31530,238.00400,289.5251,593.17920,NaN,Central Electricity Authority,NaN

In [17]:
data.info

<bound method DataFrame.info of     country country_long                          name   gppd_idnr  \
0       IND        India              ACME Solar Tower  WRI1020239
1       IND        India           ADITYA CEMENT WORKS  WRI1019881
2       IND        India      AES Saurashtra Windfarms  WRI1026669
3       IND        India                   AGARTALA GT  IND0000001
4       IND        India                  AKALTARA TPP  IND0000002
..      ...          ...                           ...         ...
902     IND        India                  YERMARUS TPP  IND0000513
903     IND        India  Yelesandra Solar Power Plant  WRI1026222
904     IND        India  Yelisirur wind power project  WRI1026776
905     IND        India                   ZAWAR MINES  WRI1019901
906     IND        India       iEnergy Theni Wind Farm  WRI1026761

     capacity_mw  latitude  longitude primary_fuel other_fuel1 other_fuel2  \
0            2.5   28.1839    73.2407        Solar         NaN         NaN
1           98.0   24.7663    74.6090         Coal         NaN         NaN
2           39.2   21.9038    69.3732         Wind         NaN         NaN
3          135.0   23.8712    91.3602          Gas         NaN         NaN
4         1800.0   21.9603    82.4091         Coal         Oil         NaN
..           ...       ...        ...          ...         ...         ...
902       1600.0   16.2949    77.3568         Coal         Oil         NaN
903          3.0   12.8932    78.1654        Solar         NaN         NaN
904         25.5   15.2758    75.5811         Wind         NaN         NaN
905         80.0   24.3500    73.7477         Coal         NaN         NaN
906         16.5    9.9344    77.4768         Wind         NaN         NaN

     ...  year_of_capacity_data  generation_gwh_2013 generation_gwh_2014  \
0    ...                    NaN                  NaN                 NaN
1    ...                    NaN                  NaN                 NaN
2    ...                    NaN                  NaN                 NaN
3    ...                 2019.0                  NaN          617.789264
4    ...                 2019.0                  NaN         3035.550000
..   ...                    ...                  ...                 ...
902  ...                 2019.0                  NaN                 NaN
903  ...                    NaN                  NaN                 NaN
904  ...                    NaN                  NaN                 NaN
905  ...                    NaN                  NaN                 NaN
906  ...                    NaN                  NaN                 NaN

    generation_gwh_2015 generation_gwh_2016 generation_gwh_2017  \
0                   NaN                 NaN                 NaN
1                   NaN                 NaN                 NaN
2                   NaN                 NaN                 NaN
3            843.747000          886.004428          663.774500
4           5916.370000         6243.000000         5385.579736
..                  ...                 ...                 ...
902            0.994875          233.596650          865.400000
903                 NaN                 NaN                 NaN
904                 NaN                 NaN                 NaN
905                 NaN                 NaN                 NaN
906                 NaN                 NaN                 NaN

     generation_gwh_2018  generation_gwh_2019         generation_data_source  \
0                    NaN                  NaN                            NaN
1                    NaN                  NaN                            NaN
2                    NaN                  NaN                            NaN
3             626.239128                  NaN  Central Electricity Authority
4            7279.000000                  NaN  Central Electricity Authority
..                   ...                  ...                            ...
902           686.500000                  NaN  Central Electricity Authority
903                  NaN                  NaN                            NaN
904                  NaN                  NaN                            NaN
905                  NaN                  NaN                            NaN
906                  NaN                  NaN                            NaN

     estimated_generation_gwh
0                         NaN
1                         NaN
2                         NaN
3                         NaN
4                         NaN
..                        ...
902                       NaN
903                       NaN
904                       NaN
905                       NaN
906                       NaN

[907 rows x 27 columns]>

In [18]:
data.isnull().sum()

country                       0
country_long                  0
name                          0
gppd_idnr                     0
capacity_mw                   0
latitude                     46
longitude                    46
primary_fuel                  0
other_fuel1                 709
other_fuel2                 906
other_fuel3                 907
commissioning_year          380
owner                       565
source                        0
url                           0
geolocation_source           19
wepp_id                     907
year_of_capacity_data       388
generation_gwh_2013         907
generation_gwh_2014         509
generation_gwh_2015         485
generation_gwh_2016         473
generation_gwh_2017         467
generation_gwh_2018         459
generation_gwh_2019         907
generation_data_source      458
estimated_generation_gwh    907
dtype: int64

In [19]:
data.drop(columns=['wepp_id','year_of_capacity_data','generation_gwh_2013','generation_gwh_2014','generation_gwh_2015','generation_gwh_2016','generation_gwh_2017','generation_gwh_2018','generation_gwh_2019','generation_data_source','estimated_generation_gwh','other_fuel1','other_fuel2','other_fuel3','commissioning_year','owner','url','country','country_long','name','source','geolocation_source'],inplace=True)

In [20]:
data

      gppd_idnr  capacity_mw  latitude  longitude primary_fuel
0    WRI1020239          2.5   28.1839    73.2407        Solar
1    WRI1019881         98.0   24.7663    74.6090         Coal
2    WRI1026669         39.2   21.9038    69.3732         Wind
3    IND0000001        135.0   23.8712    91.3602          Gas
4    IND0000002       1800.0   21.9603    82.4091         Coal
..          ...          ...       ...        ...          ...
902  IND0000513       1600.0   16.2949    77.3568         Coal
903  WRI1026222          3.0   12.8932    78.1654        Solar
904  WRI1026776         25.5   15.2758    75.5811         Wind
905  WRI1019901         80.0   24.3500    73.7477         Coal
906  WRI1026761         16.5    9.9344    77.4768         Wind

[907 rows x 5 columns]

In [21]:
data=data.dropna()

In [22]:
data

      gppd_idnr  capacity_mw  latitude  longitude primary_fuel
0    WRI1020239          2.5   28.1839    73.2407        Solar
1    WRI1019881         98.0   24.7663    74.6090         Coal
2    WRI1026669         39.2   21.9038    69.3732         Wind
3    IND0000001        135.0   23.8712    91.3602          Gas
4    IND0000002       1800.0   21.9603    82.4091         Coal
..          ...          ...       ...        ...          ...
902  IND0000513       1600.0   16.2949    77.3568         Coal
903  WRI1026222          3.0   12.8932    78.1654        Solar
904  WRI1026776         25.5   15.2758    75.5811         Wind
905  WRI1019901         80.0   24.3500    73.7477         Coal
906  WRI1026761         16.5    9.9344    77.4768         Wind

[861 rows x 5 columns]

In [23]:
data['gppd_idnr'].nunique()

861

In [24]:
data['primary_fuel'].value_counts()

Coal       253
Hydro      233
Solar      123
Wind       108
Gas         68
Biomass     50
Oil         17
Nuclear      9
Name: primary_fuel, dtype: int64

In [25]:
data['primary_fuel']=LabelEncoder().fit_transform(data['primary_fuel'])
data['gppd_idnr']=LabelEncoder().fit_transform(data['gppd_idnr'])

C:\Users\20poo\AppData\Local\Temp\ipykernel_6048\56201242.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['primary_fuel']=LabelEncoder().fit_transform(data['primary_fuel'])
C:\Users\20poo\AppData\Local\Temp\ipykernel_6048\56201242.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['gppd_idnr']=LabelEncoder().fit_transform(data['gppd_idnr'])

In [26]:
data

     gppd_idnr  capacity_mw  latitude  longitude  primary_fuel
0          629          2.5   28.1839    73.2407             6
1          492         98.0   24.7663    74.6090             1
2          818         39.2   21.9038    69.3732             7
3            0        135.0   23.8712    91.3602             2
4            1       1800.0   21.9603    82.4091             1
..         ...          ...       ...        ...           ...
902        468       1600.0   16.2949    77.3568             1
903        787          3.0   12.8932    78.1654             6
904        846         25.5   15.2758    75.5811             7
905        512         80.0   24.3500    73.7477             1
906        831         16.5    9.9344    77.4768             7

[861 rows x 5 columns]

In [27]:
x= data.iloc[:,:-1]
y=data.iloc[:,-1]

In [28]:
x

     gppd_idnr  capacity_mw  latitude  longitude
0          629          2.5   28.1839    73.2407
1          492         98.0   24.7663    74.6090
2          818         39.2   21.9038    69.3732
3            0        135.0   23.8712    91.3602
4            1       1800.0   21.9603    82.4091
..         ...          ...       ...        ...
902        468       1600.0   16.2949    77.3568
903        787          3.0   12.8932    78.1654
904        846         25.5   15.2758    75.5811
905        512         80.0   24.3500    73.7477
906        831         16.5    9.9344    77.4768

[861 rows x 4 columns]

In [29]:
y

0      6
1      1
2      7
3      2
4      1
      ..
902    1
903    6
904    7
905    1
906    7
Name: primary_fuel, Length: 861, dtype: int32

In [31]:
X_train, X_test,y_train, y_test = train_test_split(x,y,random_state=104,test_size=0.20, shuffle=True)

In [33]:
classifier = SVC(kernel='linear', random_state=0)  
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [34]:
y_pred= classifier.predict(X_test)

In [35]:
y_pred

array([1, 3, 3, 3, 3, 3, 6, 1, 3, 1, 3, 3, 7, 3, 0, 1, 6, 6, 3, 1, 6, 6,
       1, 5, 6, 1, 6, 6, 1, 3, 3, 7, 3, 3, 1, 1, 1, 0, 1, 1, 1, 1, 3, 1,
       1, 7, 3, 3, 1, 3, 1, 0, 3, 7, 3, 1, 3, 3, 6, 6, 0, 1, 6, 0, 1, 3,
       6, 6, 3, 1, 1, 3, 3, 7, 3, 3, 1, 3, 3, 7, 3, 1, 1, 3, 5, 1, 3, 1,
       1, 3, 6, 1, 3, 1, 1, 1, 7, 7, 7, 3, 0, 6, 7, 1, 3, 1, 0, 7, 0, 1,
       1, 1, 3, 3, 6, 7, 1, 6, 6, 7, 1, 1, 6, 1, 3, 6, 1, 7, 3, 1, 3, 1,
       3, 1, 1, 0, 6, 3, 3, 5, 1, 7, 3, 1, 6, 3, 1, 0, 7, 7, 7, 1, 3, 1,
       3, 7, 1, 3, 3, 3, 1, 3, 1, 1, 1, 1, 1, 6, 6, 3, 3, 3, 1])

In [37]:
cm= confusion_matrix(y_test, y_pred)

In [38]:
cm

array([[ 8,  3,  0,  0,  0,  0,  0,  0],
       [ 2, 39,  0, 13,  0,  1,  0,  0],
       [ 0,  8,  0, 10,  0,  2,  0,  0],
       [ 0,  9,  0, 32,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 22,  7],
       [ 0,  0,  0,  0,  0,  0,  2, 12]], dtype=int64)